import { Check, CreditCard } from "lucide-react"
import { KpiCard } from "@/components/patterns/kpi-card"
import { WorkspacePage } from "@/components/patterns/workspace-page"

export default function BillingPage() {
  return <WorkspacePage prototipo="cobrança (fase 7)" eyebrow="Configuração" title="Plano e cobrança" description="Acompanhe seu plano, consumo e forma de pagamento em um só lugar.">
    <section className="grid gap-4 md:grid-cols-3"><KpiCard label="Plano atual" value="Growth" detail={<span className="text-ink-2">Renova em 24 dias</span>} icon={<CreditCard />} /><KpiCard label="Conversas usadas" value="1.284" detail={<span className="text-ink-2">de 5.000 no ciclo</span>} icon={<Check />} /><KpiCard label="Próxima cobrança" value="R$ 499" detail={<span className="text-ink-2">21 de outubro</span>} icon={<CreditCard />} /></section>
    <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-card border border-hairline bg-surface-1 p-6"><h2 className="font-display text-lg text-ink-1">Seu plano Growth</h2><p className="mt-2 text-sm leading-6 text-ink-2">Automação completa para clínicas em crescimento, com agentes ilimitados e suporte prioritário.</p><div className="mt-6 flex flex-col gap-3 text-sm text-ink-1">{["Até 5.000 conversas por mês", "Agentes ilimitados", "Analytics avançado", "Suporte prioritário"].map((item) => <div key={item} className="flex items-center gap-2"><Check className="size-4 text-success-fg" />{item}</div>)}</div><button type="button" className="mt-6 rounded-lg border border-hairline px-4 py-2 text-sm font-semibold text-ink-1 hover:border-brand">Gerenciar plano</button></div><div className="rounded-card border border-hairline bg-surface-1 p-6"><h2 className="font-display text-lg text-ink-1">Forma de pagamento</h2><div className="mt-5 rounded-xl border border-hairline p-4"><p className="text-sm font-medium text-ink-1">Visa terminando em 4242</p><p className="mt-1 text-xs text-ink-2">Próxima cobrança automática</p></div><button type="button" className="mt-4 text-sm font-medium text-brand-on-light hover:underline dark:text-brand">Atualizar cartão</button></div></div>
  </WorkspacePage>
}
