-- Baseline das tabelas que já existiam no banco antes do SaaS.
--
-- O projeto Supabase é compartilhado com a landing (nextech.ia.br), que está
-- em produção desde antes destas migrations. Estas tabelas foram criadas pelo
-- Dashboard, sem migration correspondente — este arquivo traz o estado delas
-- para o versionamento, cumprindo a regra 1 do CLAUDE.md.
--
-- Achado da revisão de segurança de 2026-09-16: sem esta baseline, um
-- ambiente novo (`supabase db reset`, projeto de staging) subiria
-- `chatbot_leads` SEM RLS. A falha seria silenciosa, porque a rota da landing
-- escreve com service_role e continuaria funcionando — ninguém perceberia
-- até alguém listar PII com a anon key, que é pública por estar no JS do site.
--
-- `if not exists` em tudo: no projeto de produção estes objetos já existem, e
-- a migration precisa ser idempotente para não quebrar o `db push`.

-- ─────────────────────────────────────────────────────────────
-- chatbot_leads — captura de lead do chatbot da landing.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.chatbot_leads (
  id uuid primary key default gen_random_uuid(),
  name text,            -- PII
  email text,           -- PII
  whatsapp text,        -- PII
  company text,
  specialty text,
  meetings_count text,
  origem text,
  created_at timestamptz default now()
);

comment on table public.chatbot_leads is
  'Lead capturado pelo chatbot da landing. Contém PII (nome, e-mail, '
  'WhatsApp). Escrita só por service_role, pela rota app/api/chatbot. '
  'Sem policy de leitura: nada é legível pela anon key.';

-- RLS sem nenhuma policy = ninguém com anon key lê ou escreve.
-- A rota da landing usa service_role, que ignora RLS por definição, então
-- a captura de lead continua funcionando.
alter table public.chatbot_leads enable row level security;

-- ─────────────────────────────────────────────────────────────
-- projetoAtivo — tabela legada da landing.
--
-- Nenhum código do repositório a referencia (verificado em 2026-09-16).
-- Mantida aqui para que o schema versionado corresponda ao real. Se for
-- confirmada como resíduo, remover em migration própria — não silenciosamente.
-- ─────────────────────────────────────────────────────────────
create table if not exists public."projetoAtivo" (
  id bigint primary key generated by default as identity,
  created_at timestamptz default now(),
  "Ativo" text
);

alter table public."projetoAtivo" enable row level security;
